###Look all Characters
GET http://localhost:8000/characters


###Look 1 Character
GET http://localhost:8000/characters/1

###Post 1 Character
POST http://localhost:8000/characters
Content-Type: application/json

{
    "characterName": "Horick",
    "characterPhysique": 40,
    "characterSocial": 30,
    "characterMental": 30,
    "characterStory": "ancein gerrier de memoria reconverte dans me mersenaria"
}


###PUT 1 Character
PUT http://localhost:8000/put/characters/2
Content-Type: application/json

{
    "characterName": "Eldar",
    "characterPhysique": 40,
    "characterSocial": 30,
    "characterMental": 30,
    "characterStory": "Premier homme dechu"
}

###delette 1 Character

DELETE http://localhost:8000/del/characters/2